### ISSUE TITLE
Support for v8.1?

### ISSUE THREAD

**Issue by LottePitcher** [leekelleher/umbraco-robotstxt-editor#17]
Hey @leekelleher ,

We know that this worked on Umbraco v8.1 as that was the version we initially developed on. Could we allow the package to be available to that earlier version rather than targeting a min of 8.2? Perhaps you don’t think it’s worth it and we just stick to 8.2+

Just an idea!
Lotte

**Comment by leekelleher** [comment]
Quick answer is **yes**, we could set the minimum version to 8.1, (or even 8.0).

My general stance when initially releasing an Umbraco package is that no one has used it before, so they'd only use it on new project builds. So I set the minimum dependency to the latest Umbraco version.

But then for a utility package like this, it could be retrofitted, so yeah - there's no technical reason why we can't lower the minimum dependency version.

**Comment by LottePitcher** [comment]
That makes sense @leekelleher.  

I'm tempted to give it a try so I can go through the process of releasing an update (again!).

Am I right that the work required is along the lines of:
- downgrade the umbraco version used in the package
- test all still works
- update any documentation that makes reference to 8.2 to 8.1
- PR and get that approved/merged
- re-run build scripts to generate new version of Our and nuget package files and upload those
- update the min version supported in Our

Does that sound vaguely right?  Am happy to give this a go if so.

Would the next version be 8.0.1, or 8.1.0?

**Comment by leekelleher** [comment]
The steps are correct! 👍 

Next version number, this is where we get into the semantics of SemVer, _(that is, if we're following it?)_

With SemVer...
- Bug fixes are meant to be patch releases, e.g. v8.0.1
- New features are meant to be minor releases, e.g. v8.1.0.
- Breaking changes are meant to be major releases, e.g. v9.0.0.

For this, I'd go with v8.0.1, because it's early days of the package.

**Comment by LottePitcher** [comment]
@leekelleher I'm going to close this issue as it's a bit pointless now that umbraco is on v8.5!  I've tested the package on v8.5, by the way, still works ;-)
