### ISSUE TITLE
Tree - could not be resolved to a .Net object type

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-robotstxt-editor#2]
> Reference: https://our.umbraco.org/projects/developer-tools/robotstxt-editor/feedback/74747-could-not-be-resolved-to-a-net-object-type
### Error

When installing the package on Umbraco v6.2.5, the tree item is not loaded in the back-office and the following error can be found in the "/App_Data/Logs/UmbracoTraceLog.txt"...

```
2016-02-01 14:45:17,797 [9] WARN  umbraco.BusinessLogic.ApplicationTree - [Thread 23] The tree definition: <add silent="false" initialize="true" sortOrder="6" alias="robotsTxt" application="developer" title="Robots.txt" iconClosed="../../robots-txt/robot.png" iconOpen="../../robots-txt/robot.png" assembly="Our.Umbraco.Tree.RobotsTxt" type="RobotsTxtTree" action="" /> could not be resolved to a .Net object type
```
### Workaround fix

A workaround fix is to manually amend the entry in the "/config/trees.config" file...

``` xml
<add silent="false" initialize="true" sortOrder="6" alias="robotsTxt" application="developer" title="Robots.txt" iconClosed="../../robots-txt/robot.png" iconOpen="../../robots-txt/robot.png" type="Our.Umbraco.Tree.RobotsTxt.RobotsTxtTree, Our.Umbraco.Tree.RobotsTxt" action="" />
```
### Notes

I'm not sure what changed in Umbraco v6.2.5 to make the syntax invalid.  Also I don't know if this is an issue with recent Umbraco versions (v7+).

**I would like a community member to pick this issue up.  It is a low-hanging fruit; it would be ideal for someone who wanted to get involved with Umbraco package development/community.**

**Comment by dtila** [comment]
The reason you have this error, is because you renamed the controller or the namespace which was placed. Because of that, the type can not be loaded, so you need to clean manually the tree.config file. 

If you delete manually the records, these will be generated again by Umbraco

**Comment by leekelleher** [comment]
Closing this ticket, no further development is being done to the legacy version of this package.
Support for Umbraco v8.x will be continued.
