### ISSUE TITLE
Robots.txt Disappears

### ISSUE THREAD

**Issue by bob-2165** [leekelleher/umbraco-robotstxt-editor#3]
Hi, I've installed this package via the packages in the back office in umbraco. I'm running 7.5.13. I noticed that out of no where the robots.txt file disappears in the back office (the robot logo file). I uninstalled things, then installed via nuget hoping this would fix things...no luck, same issue - it disappears. Not sure how to get it back.

**Comment by leekelleher** [comment]
Thanks for getting in touch @bobi33.

I'm closing this ticket as I've replied on your forum post:
<https://our.umbraco.org/projects/developer-tools/robotstxt-editor/feedback/85410-robotstxt-disappears-in-back-office>
