### ISSUE TITLE
Support for Umbraco v8

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-robotstxt-editor#4]
## Would you like to develop an Umbraco package?

**Calling all newcomers to Umbraco package development!**
Have you ever wanted to develop an Umbraco package, but didn't know where to start? 

[Robots.txt Editor](https://our.umbraco.com/packages/developer-tools/robotstxt-editor/) was one of the first packages that I developed for Umbraco... _nearly 10 years ago!_

It was a great learning ground, I had to figure out how to add a custom tree to the Developer section, create an editor panel, do validation and display notifications in the back-office.

With upcoming release of Umbraco v8, there's an opportunity for this package to be re-imagined for v8, with lots of learnings!

**If you are new to Umbraco package development, and would like to be involved in the next wave of pioneering Umbraco v8, this is an ideal opportunity for you!**

I'm happy to consult, mentor, offer general chit-chat. It'd be great to see fresh blood in the Umbraco package ecosystem!

**Comment by leekelleher** [comment]
@emmaburstow [Following up on Twitter...](https://twitter.com/EmaBurst/status/1097972229604864000) off the top of my head, first few pointers would be...

- [ ] Learn how to add a custom tree to a section (whatever the "Developer" section is now called in v8?)
- [ ] Figure out how to wire up the tree node with the editor panel. This would be completely different to how I've done it in this repo, WebForms is gone, it's 100% AngularJs in v8.
- [ ] Once you've got the editor panel in place, (which is pretty much a really big textarea), then could look at adding buttons in (to insert the various Robots.txt rules).
- [ ] After that, it's how to validate the Robots.txt content. I assume this is still server-side/C#.
- [ ] Then figure out how to display notifications, for success/failure statuses.


_Not to overwhelm you or anything!_ 😆 There's probably a few more things I've forgot, I'll update here if I think of anything else ☺️

**Comment by leekelleher** [comment]
Oh lordy, I didn't even mention any of the "packaging" stuff... but let's not worry about that side of it for now, that'll come in due course! 😄

**Comment by emmaburstow** [comment]
Yay! Did I get the job then?

Don't worry about overwhelm. I work really well with a checklist approach. I'll get started on the first of the boxes tomorrow. 😁

**Comment by LottePitcher** [comment]
@leekelleher @emmaburstow if it would be useful to have a pBuddy for this (p for 'package', obviously) then I'd be available. Not done a package myself, yet, so not offering guidance but mutual learning! I would be available for remote and non-remote (real/physical?!) collaboration...

**Comment by MMasey** [comment]
@leekelleher This is an awesome idea. Can i get involved too?

**Comment by leekelleher** [comment]
@emmaburstow @LottePitcher @MMasey OK cool, the ball is your court! 🏐
I'll make myself available for if/when you need any advice or bounce ideas around.
_(However this "mentoring" part should work? - it's learning curve for me too!)_ 😃

**Comment by leekelleher** [comment]
I've archived off the old code to a branch called [`legacy`](https://github.com/leekelleher/umbraco-robotstxt-editor/tree/legacy), (if you need to reference it), and given you a clean slate in the `develop` branch... the world's your oyster!

**Comment by osigas** [comment]
I'd like to get involved too @leekelleher, great way to start with V8

**Comment by leekelleher** [comment]
Hi @osigas, thanks for reaching out, it's appreciated. 🙏 

I believe the others have already started work on this, I doubt there's much left in terms of sharing out the workload (for this specific package).

Of course, there'll be various learnings from this, so please do feel free to keep an eye on the progress and contribute if/when you want to.  Thanks again!
