### ISSUE TITLE
Umbraco 7 save.gif error

### ISSUE THREAD

**Issue by sekmenhuseyin** [leekelleher/umbraco-robotstxt-editor#8]
In umbraco 7 your package can not find save.gif

**GET https://localhost:44313/umbraco/images/editor/save.gif 404 ()
17:59:01.269** 

![image](https://user-images.githubusercontent.com/1363876/56971218-82b6b800-6b71-11e9-9cbd-aad020c7eb27.png)

**Comment by leekelleher** [comment]
@sekmenhuseyin Which version of Umbraco is this?

**Comment by leekelleher** [comment]
Turns out that the image was removed in Umbraco v7.7.0.

The original image is still available here: https://github.com/umbraco/Umbraco-CMS/blob/release-7.6.13/src/Umbraco.Web.UI/umbraco/images/editor/Save.GIF
If you wanted to download it and put it in the `/umbraco/images/editor/save.gif` path?
